[ 2025-09-29 12:12:03,794 12 root - INFO - Initiate the data ingestion
[ 2025-09-29 12:12:03,794 93 root - INFO - Exporting collection data as pandas dataframe
[ 2025-09-29 12:12:05,445 17 root - ERROR - An unhandled exception occurred: Erro Occured in python script name [E:\NetworkSecurity\networksecurity\components\data_ingestion.py] line number [97] erro message [The dataframe is empty. Please check the MongoDB collection and connection details.]
